---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.94, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Random
no_index:
  directory:
    - t
    - inc
requires:
  Encode::Locale: 1.01
  JSON: 2.9
  LWP::UserAgent: 0
  Test::MockObject: 1.07
  Test::More: 0.64
resources: {}
version: 2.31
