--- #YAML:1.0
name:                Net-Random
version:             2.0
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    LWP::UserAgent:                0
    Test::MockObject:              1.07
    Test::More:                    0.64
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
